FROM nfcore/base
LABEL authors="Chelsea Sawyer" \
      description="Docker image containing cellranger requirements for nf-core/demultiplex pipeline"

COPY environment_cellranger.yml /
RUN conda env create -f /environment_cellranger.yml && conda clean -a
ENV PATH /opt/conda/envs/nf-core-demultiplex-cellranger-1.0dev/bin:$PATH
